# docu: https://luna.gitlab.io/hypercorn/how_to_guides/configuring.html#configuration-options

[server]
bind = ["0.0.0.0:8000"]    # Adresse IP et port
workers = 4                # Nombre de processus travailleurs
keep_alive = 30            # Temps d'attente avant de fermer une connexion inactive

[logging]
loglevel = "info"           # Niveau de journalisation
accesslog = "logs/public.log"    # Fichier pour les journaux d'acc√®s
errorlog = "logs/error.log"      # Fichier pour les erreurs